server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_table?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123

mybatis:
  mapper-locations: classpath:com/jxedt/mapper/*.xml
  config-location: classpath:mybatis-config.xml
